---
swagger: "2.0"
info:
  description: "Simple Visitor Management User Authentication Service API"
  version: "0.0.3"
  title: "SMV User Auth Service API"
host: "localhost:6002"
basePath: "/api/smv/v1/auth"
schemes:
- "http"
- "https"
produces:
- "application/json"
paths:
  /login:
    post:
      tags:
      - "사용자인증"
      summary: "주어진 인증 정보로 로그인"
      operationId: "loginPOST"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - name: "email"
        in: "formData"
        description: "사용자 Email"
        required: true
        type: "string"
      - name: "passwd"
        in: "formData"
        description: "사용자 비밀번호"
        required: true
        type: "string"
      responses:
        200:
          description: "로그인 성공"
          headers:
            X-AUTH-TOKEN:
              type: "string"
              description: "Authentication Token"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/inline_response_default"
      x-swagger-router-controller: ""
  /logout:
    get:
      tags:
      - "사용자인증"
      summary: "로그인 상태에서 로그아웃"
      operationId: "logoutGET"
      produces:
      - "application/json"
      parameters:
      - name: "X-AUTH-TOKEN"
        in: "header"
        description: "인증 토큰"
        required: true
        type: "string"
      responses:
        200:
          description: "로그아웃 성공"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/inline_response_default"
      x-swagger-router-controller: ""
  /userinfo:
    get:
      tags:
      - "사용자인증"
      summary: "로그인한 사용자의 정보를 조회"
      operationId: "userinfoGET"
      produces:
      - "application/json"
      parameters:
      - name: "X-AUTH-TOKEN"
        in: "header"
        description: "인증 토큰"
        required: true
        type: "string"
      responses:
        200:
          description: "인증된 사용자 정보"
          schema:
            $ref: "#/definitions/inline_response_200"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/inline_response_default"
      x-swagger-router-controller: ""
definitions:
  UserObject:
    type: "object"
    properties:
      userid:
        type: "string"
        example: "CN=John Doe/OU=ACME/O=IBM"
        description: "사용자 ID"
      serial:
        type: "string"
        example: "1234567890"
        description: "사용자 사번"
      name:
        type: "string"
        example: "John Doe"
        description: "사용자 성명"
      phone:
        type: "string"
        example: "+82-2-1234-0000"
        description: "유선전화번호"
      mobile:
        type: "string"
        example: "+82-10-1234-0000"
        description: "휴대전화번호"
      email:
        type: "string"
        example: "john.doe@acme.ibm.com"
        description: "이메일 연락처"
      role:
        type: "string"
        description: "사용자 역할 정보"
        enum:
        - "RECEPTION"
        - "ESCORT"
        - "ADMIN"
  Error:
    type: "object"
    properties:
      error:
        type: "string"
        example: "failed to get document"
      reason:
        type: "string"
        example: "insufficient parameter"
      statusCode:
        type: "integer"
        format: "int32"
        example: 500
  inline_response_default:
    properties:
      error:
        type: "string"
        example: "failed to get document"
      reason:
        type: "string"
        example: "insufficient parameter"
      statusCode:
        type: "integer"
        format: "int32"
        example: 500
  inline_response_200:
    properties:
      userid:
        type: "string"
        example: "CN=John Doe/OU=ACME/O=IBM"
        description: "사용자 ID"
      serial:
        type: "string"
        example: "1234567890"
        description: "사용자 사번"
      name:
        type: "string"
        example: "John Doe"
        description: "사용자 성명"
      phone:
        type: "string"
        example: "+82-2-1234-0000"
        description: "유선전화번호"
      mobile:
        type: "string"
        example: "+82-10-1234-0000"
        description: "휴대전화번호"
      email:
        type: "string"
        example: "john.doe@acme.ibm.com"
        description: "이메일 연락처"
      role:
        type: "string"
        description: "사용자 역할 정보"
        enum:
        - "RECEPTION"
        - "ESCORT"
        - "ADMIN"
