swagger: '2.0'
info:
  title: SMV API
  description: Simple Visitor Managment API
  version: 0.0.2
schemes:
  - http
  - https
basePath: /api/smv/v1
produces:
  - application/json
paths:
  '/user/{id}':
    get:
      summary: 주어진 id로 사용자 정보를 검색
      tags:
        - 사용자정보
      parameters:
        - name: id
          description: 사용자 ID
          in: path
          type: string
          required: true
      responses:
        '200':
          description: 사용자 정보
          schema:
            $ref: '#/definitions/UserObject'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  '/user/{id}/role/{role}':
    put:
      summary: 사용자 role 정보 변경
      tags:
        - 사용자정보
      parameters:
        - name: id
          description: 사용자 ID
          in: path
          type: string
          required: true
        - name: role
          in: path
          type: string
          required: true
      responses:
        '200':
          description: OK
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  '/auth/login':
    post:
      summary: 주어진 인증 정보로 로그인
      tags:
        - 사용자인증
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/LoginInfo'
      responses:
        '200':
          description: 로그인 성공
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  '/auth/logout':
    get:
      summary: 로그인 상태에서 로그아웃
      tags:
        - 사용자인증
      responses:
        '200':
          description: 로그아웃 성공
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  '/auth/userinfo':
    get:
      summary: 로그인한 사용자의 정보를 조회
      tags:
        - 사용자정보
      responses:
        '200':
          description: 사용자 정보
          schema:
            $ref: '#/definitions/UserObject'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  '/visit':
    post:
      summary: 방문 정보를 생성
      tags:
        - 방문정보
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/VisitingObject'
      responses:
        '200':
          description: 방문 정보 생성 성공
        '409':
          description: 기존에 존재하는 정보
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json: |-
              {
                "error": "conflict",
                "reason": "Document update conflict.",
                "statusCode": 409
              }
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  '/visit/{id}':
    get:
      summary: 주어진 id로 방문 정보 조회
      tags:
        - 방문정보
      parameters:
        - name: id
          description: 방문정보 ID
          in: path
          type: string
          required: true
      responses:
        '200':
          description: 방문 정보
          schema:
            $ref: '#/definitions/VisitingObject'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    put:
      summary: 기존 방문 정보 변경
      tags:
        - 방문정보
      parameters:
        - name: id
          description: 방문정보 ID
          in: path
          type: string
          required: true
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/VisitingObject'
      responses:
        '200':
          description: 변경 성공
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      summary: 기존 방문 정보 삭제
      tags:
        - 방문정보
      parameters:
        - name: id
          description: 방문정보 ID
          in: path
          type: string
          required: true
      responses:
        '200':
          description: 삭제 성공
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  '/visit/search':
    get:
      summary: 주어진 조건을 만족하는 모든 방문 정보 조회
      tags:
        - 방문정보
      parameters:
        - name: date
          description: 방문일시 (ex.1493349000000, 밀리초, 브라우저 시간 기준)
          in: query
          type: integer
          format: int64
        - name: type
          description: 검색 종류
          in: query
          type: string
          enum: [NONE, NAME, EMAIL, CONTACT]
        - name: keyword
          description: 검색어
          in: query
          type: string
        - name: page
          description: 페이지 인덱스 (0부터 시작)
          in: query
          type: integer
          format: int32
        - name: size
          description: 한 페이지당 아이템 갯수
          in: query
          type: integer
          format: int32
      responses:
        '200':
          description: 방문 정보 리스트
          schema:
            type: object
            properties:
              result:
                type: array
                items:
                  $ref: '#/definitions/VisitingObject'
              paging:
                $ref: '#/definitions/PagingInfo'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  '/badge':
    post:
      summary: 임시 출입증 신규 생성
      tags:
        - 임시출입증
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/BadgeObject'
      responses:
        '200':
          description: OK
        '404':
          description: Conflict
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json: |-
              {
                "error": "failed to create a room",
                "reason": "The site is not exist.",
                "statusCode": 404
              }
        '409':
          description: Conflict
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json: |-
              {
                "error": "conflict",
                "reason": "Document update conflict.",
                "statusCode": 409
              }
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  '/badge/{id}':
    get:
      summary: 임시 출입증 정보 조회
      tags:
        - 임시출입증
      parameters:
        - name: id
          description: 임시출입증 ID
          in: path
          type: string
          required: true
      responses:
        '200':
          description: 임시 출입증 정보
          schema:
            $ref: '#/definitions/BadgeObject'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    put:
      summary: 임시 출입증 정보 변경
      tags:
        - 임시출입증
      parameters:
        - name: id
          description: 임시출입증 ID
          in: path
          type: string
          required: true
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/BadgeObject'
      responses:
        '200':
          description: 임시 출입증 정보 변경 완료
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      summary: 임시 출입증 정보 삭제
      tags:
        - 임시출입증
      parameters:
        - name: id
          description: 임시 출입증 ID
          in: path
          type: string
          required: true
      responses:
        '200':
          description: 임시 출입증 정보 삭제 완료
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  VisitingObject:
    type: object
    properties:
      id:
        type: string
        description: 방문정보 ID
        example: 10103023023010
      date:
        type: string
        description: 방문정보 ID
        example: '2017-04-28 12:10:00 GMT+09:00'
      updated:
        type: integer
        format: int64
        description: 방문정보 ID
        example: 1493349000000
      visitor:
        $ref: '#/definitions/VisitorInfo'
      escort:
        $ref: '#/definitions/EscortEmployeeInfo'
      agreement:
        $ref: '#/definitions/AgreementInfo'
  BadgeObject:
    type: object
    properties:
      id:
        type: string
        description: 방문정보 ID
        example: 12392391239
      type:
        type: string
        description: 방문정보 ID
        example: VISITOR
      number:
        type: string
        description: 방문정보 ID
        example: 1
  UserObject:
    type: object
    properties:
      userid:
        type: string
        description: 사용자 ID
        example: CN=John Doe/OU=ACME/O=IBM
      serial:
        type: string
        description: 사용자 사번
        example: 1234567890
      name:
        type: string
        description: 사용자 성명
        example: John Doe
      phone:
        type: string
        description: 유선전화번호
        example: +82-2-1234-0000
      mobile:
        type: string
        description: 휴대전화번호
        example: +82-10-1234-0000
      email:
        type: string
        description: 이메일 연락처
        example: john.doe@acme.ibm.com
      role:
        type: string
        description: 사용자 역할 정보
        enum:
          - RECEPTION
          - ESCORT
          - ADMIN
  VisitorInfo:
    type: object
    properties:
      name:
        type: string
        description: 방문자 성명
        example: 'Jane Doe'
      title:
        type: string
        description: 방문자 직함
        example: Dr.
      contact:
        type: string
        description: 방문자 연락처
        example: +82-1-1234-0678
      email:
        type: string
        description: 방문자 이메일
        example: jane.doe@customer.com
      nationality:
        type: string
        description: 방문자 국적(영문표기)
        example: South Korea
      company:
        type: string
        description: 방문자 회사(학교, 또는 단체)
        example: Customers Inc
  EscortEmployeeInfo:
    type: object
    properties:
      id:
        type: string
        description: 에스코트 직원 ID
        example: CN=John Doe/OU=ACME/O=IBM
      name:
        type: string
        description: 에스코트 직원 성명
        example: John Doe
      email:
        type: string
        description: 에스코트 직원 이메일
        example: john.doe@acme.ibm.com
      dept:
        type: string
        description: 에스코트 직원 부서
        example: Client Innovation Lab
  AgreementInfo:
    type: object
    properties:
      templateid:
        type: string
        description: 정보동의서 양식 ID
        example: 238a8a7d77f7bf
      agreement:
        type: string
        description: 정보동의 내용
        example: User agreement blabla
      date:
        type: integer
        format: int64
        description: 정보동의 일시(ex.1493349000000, 밀리초, 브라우저 시간 기준)
        example: 1493349000000
      signature:
        type: string
        description: 정보동의 서명 정보 (이미지 Base64 Encoding)
        example: 'data:image/jpeg;base64,R0lGODlhDwAOAOYAAAAAAP'
  LoginInfo:
    type: object
    required:
      - email
      - passwd
    properties:
      email:
        type: string
        description: 방문정보 ID
        example: john.doe@acme.ibm.com
      passwd:
        type: string
        description: 방문정보 ID
        example: ibmpassw0rd
  PagingInfo:
    type: object
    properties:
      page:
        type: integer
        format: int32
        description: 현재 페이지
        example: 1
      total:
        type: integer
        format: int32
        description: 전체 페이지 갯수
        example: 10
      size:
        type: integer
        format: int32
        description: 하나의 페이지가 가진 아이템 크기
        example: 20
  Error:
    type: object
    properties:
      error:
        type: string
        example: failed to get document
      reason:
        type: string
        example: insufficient parameter
      statusCode:
        type: integer
        format: int32
        example: 500
